name: Build

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
          python -m pip install poetry
          poetry install -v
      - name: Run flake8
        run: flake8 pipen_runinfo
      - run: pwd; ls -l; ls -l example/
      - name: Run examples
        run: poetry run python example/example.py
      - name: Show generated runinfo
        run: |
          for pp in $(ls -d .pipen/*); do
            pp_name=$(basename $pp)
            for proc in $(ls -d $pp/*); do
              proc_name=$(basename $proc)
              for i in $(ls -d $proc/*); do
                echo "##[group]$pp_name/$proc_name/$(basename $i)/device"
                cat $i/job.runinfo.device
                echo "##[endgroup]"
                echo "##[group]$pp_name/$proc_name/$(basename $i)/time"
                cat $i/job.runinfo.time
                echo "##[endgroup]"
                echo "##[group]$pp_name/$proc_name/$(basename $i)/session"
                cat $i/job.runinfo.session
                echo "##[endgroup]"
              done
            done
          done

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Publish to PyPI
        run: poetry publish --build -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASSWORD }}
        if: success()
