name: Build

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v8.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Run flake8
        run: uv run flake8 pipen_runinfo
      - name: Run tests
        run: uv run pytest
      - name: Run examples
        run: uv run python examples/example.py
      - name: Show generated runinfo
        run: |
          for pp in $(ls -d .pipen/*); do
            pp_name=$(basename $pp)
            if [ $pp_name == "PipelineR" ]; then
              echo "##[group]$pp_name"
              echo "Skipped"
              echo "##[endgroup]"
              continue
            fi
            if [ $pp_name == "PipelineFish" ]; then
              echo "##[group]$pp_name"
              echo "Skipped"
              echo "##[endgroup]"
              continue
            fi
            for proc in $(ls -d $pp/*); do
              proc_name=$(basename $proc)
              for i in $(ls -d $proc/*); do
                echo "##[group]$pp_name/$proc_name/$(basename $i)/device"
                cat $i/job.runinfo.device
                echo "##[endgroup]"
                echo "##[group]$pp_name/$proc_name/$(basename $i)/time"
                cat $i/job.runinfo.time
                echo "##[endgroup]"
                echo "##[group]$pp_name/$proc_name/$(basename $i)/session"
                cat $i/job.runinfo.session
                echo "##[endgroup]"
              done
            done
          done

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v8.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Publish to PyPI
        run: |
          uv build
          uv publish --username ${{ secrets.PYPI_USER }} --password ${{ secrets.PYPI_PASSWORD }}
        if: success()
